// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRPO12_2.Data;

#nullable disable

namespace TRPO12_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306052947_AddCourceRelationManyToMany")]
    partial class AddCourceRelationManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterestGroupPolzovat", b =>
                {
                    b.Property<int>("InterestGroupsId")
                        .HasColumnType("int");

                    b.Property<int>("PolzovatsId")
                        .HasColumnType("int");

                    b.HasKey("InterestGroupsId", "PolzovatsId");

                    b.HasIndex("PolzovatsId");

                    b.ToTable("InterestGroupPolzovat");
                });

            modelBuilder.Entity("TRPO12_2.InterestGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InterestGroups");
                });

            modelBuilder.Entity("TRPO12_2.Passport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PolzovatId")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolzovatId")
                        .IsUnique();

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("TRPO12_2.Polzovat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Polzovats");
                });

            modelBuilder.Entity("TRPO12_2.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TRPO12_2.UserInterestGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("InterestGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("JoinedAt")
                        .HasColumnType("date");

                    b.HasKey("UserId", "InterestGroupId");

                    b.HasIndex("InterestGroupId");

                    b.ToTable("UserInterestGroups");
                });

            modelBuilder.Entity("TRPO12_2.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolzovatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolzovatId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("InterestGroupPolzovat", b =>
                {
                    b.HasOne("TRPO12_2.InterestGroup", null)
                        .WithMany()
                        .HasForeignKey("InterestGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRPO12_2.Polzovat", null)
                        .WithMany()
                        .HasForeignKey("PolzovatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TRPO12_2.Passport", b =>
                {
                    b.HasOne("TRPO12_2.Polzovat", "Student")
                        .WithOne("Passport")
                        .HasForeignKey("TRPO12_2.Passport", "PolzovatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TRPO12_2.Polzovat", b =>
                {
                    b.HasOne("TRPO12_2.Role", "Role")
                        .WithMany("Polzovats")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TRPO12_2.UserInterestGroup", b =>
                {
                    b.HasOne("TRPO12_2.InterestGroup", "InterestGroup")
                        .WithMany("UserInterestGroups")
                        .HasForeignKey("InterestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRPO12_2.Polzovat", "Polzovat")
                        .WithMany("UserInterestGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterestGroup");

                    b.Navigation("Polzovat");
                });

            modelBuilder.Entity("TRPO12_2.UserProfile", b =>
                {
                    b.HasOne("TRPO12_2.Polzovat", "Polzovat")
                        .WithOne("Profile")
                        .HasForeignKey("TRPO12_2.UserProfile", "PolzovatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polzovat");
                });

            modelBuilder.Entity("TRPO12_2.InterestGroup", b =>
                {
                    b.Navigation("UserInterestGroups");
                });

            modelBuilder.Entity("TRPO12_2.Polzovat", b =>
                {
                    b.Navigation("Passport")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("UserInterestGroups");
                });

            modelBuilder.Entity("TRPO12_2.Role", b =>
                {
                    b.Navigation("Polzovats");
                });
#pragma warning restore 612, 618
        }
    }
}
